server:
  port: 27004

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:27001/productdb
    username: mariadb
    password: mariadb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: localhost
    port: 27002
    username: guest
    password: guest

product:
  saved: Product saved
  error: Error saving product
